[project]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "A json library for Mojo"
name = "emberjson"
platforms = ["linux-64"]
version = "0.1.9"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/bgreni/EmberJson"
repository = "https://github.com/bgreni/EmberJson"

[tasks]
# build = { cmd = "bash scripts/build.sh", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo", REPO_URL = "https://conda.modular.com/max-nightly"} }
build = { cmd = "rattler-build build --recipe recipes -c https://conda.modular.com/max-nightly -c conda-forge --skip-existing=all", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "bash scripts/publish.sh", env = {CONDA_BLD_PATH = "output", PREFIX_CHANNEL = "mojo-libs-f0cii-nightly-test"} }
template = { cmd = "magic run python3 scripts/templater.py" }
format = { cmd = "magic run mojo format -l 120 ember_json" }
test = { cmd = "magic run mojo test" }
bench = { cmd = "magic run mojo build bench.mojo && ./bench && rm bench" }

[dependencies]
max = ">=24.6.0.dev2024101817, <=25"
